# Generated by Django 5.1.1 on 2026-06-05 15:20

import django.core.validators
import reviews.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Год выпуска не может быть отрицательным!'), django.core.validators.MaxValueValidator(reviews.utils.current_year, message='Год выпуска не может быть больше текущего!')]),
        ),
    ]
